<?php

/**
 * @file
 * Primary module hooks for farmOS Regen Digital module.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function farm_regen_digital_menu_links_discovered_alter(&$links) {

  // Change the help.main menu link route to the regen digital help page.
  if (isset($links['help.main'])) {
    $links['help.main']['route_name'] = 'farm_regen_digital.help_page';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_regen_digital_preprocess_toolbar(&$variables) {
  $variables['#attached']['library'][] = 'farm_regen_digital/toolbar';
}
